# Generated by Django 2.0.1 on 2018-01-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('video_link', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
