# Generated by Django 2.0.1 on 2018-01-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180124_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('WW', 'Wood Working'), ('SP', 'Sports')], max_length=2),
        ),
    ]
