# Generated by Django 2.0.1 on 2018-01-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180127_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('Wood Working', 'Wood Working'), ('Sports', 'Sports')], max_length=100),
        ),
    ]
